{
  "openapi": "3.0.1",
  "info": {
    "title": "Arc API Docs",
    "description": "An API for the Arc platform.",
    "termsOfService": "https://onarc.io/terms",
    "license": {
      "name": "License",
      "url": "https://onarc.io/license"
    },
    "version": "1.0",
    "x-logo": {
      "url": "https://www.onarc.io/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo_arc.9cf6e0e6.svg&w=828&q=75",
      "altText": "Arc logo"
    }
  },
  "servers": [
    {
      "url": "https://testnet-api.onarc.io",
      "description": "Testnet server (uses test data)."
    },
    {
      "url": "https://api.onarc.io",
      "description": "Mainnet server (uses live data)."
    }
  ],
  "paths": {
    "/api/v1/fees": {
      "post": {
        "tags": [
          "Fee"
        ],
        "summary": "Configure Fee Model",
        "description": "This endpoint allows to configure the fee model for a specific operation.",
        "operationId": "ConfigureFeeModel"
      }
    },
    "/api/v1/fees/{feeId}": {
      "get": {
        "tags": [
          "Fee"
        ],
        "summary": "Get Fee Model",
        "description": "This endpoint fetches a configured operation fee by ID.",
        "operationId": "GetFeeModel"
      }
    },
    "/api/v1/marketplace/sell-details": {
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Get sell offer details",
        "description": "This endpoint returns the details for a sell offer in the public marketplace.",
        "operationId": "SellOfferDetails",
        "security": [
          {
            "apikey": [
              "write:sell-offers"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/sell": {
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Register sell offer",
        "description": "This endpoint registers a sell offer in the public marketplace.",
        "operationId": "RegisterSellOffer",
        "security": [
          {
            "apikey": [
              "write:sell-offers"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/sell/{offerId}": {
      "delete": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Delete sell offer",
        "description": "This endpoint deletes a sell offer in the public marketplace.",
        "operationId": "DeleteSellOffer",
        "security": [
          {
            "apikey": [
              "write:sell-offers"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/sell-offers": {
      "get": {
        "tags": [
          "Marketplace"
        ],
        "summary": "List sell offers",
        "description": "This endpoint returns a paginated list of sell offer in the public marketplace.",
        "operationId": "ListSellOffers",
        "security": [
          {
            "apikey": [
              "read:sell-offers"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/buy-details": {
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Get buy order details",
        "description": "This endpoint returns the details for a buy order in the public marketplace.",
        "operationId": "BuyOrderDetails",
        "security": [
          {
            "apikey": [
              "write:buy-orders"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/buy": {
      "post": {
        "tags": [
          "Marketplace"
        ],
        "summary": "Register buy order",
        "description": "This endpoint buys a product listed in the public marketplace.",
        "operationId": "RegisterBuyOrder",
        "security": [
          {
            "apikey": [
              "write:buy-orders"
            ]
          }
        ]
      }
    },
    "/api/v1/marketplace/buy-orders": {
      "get": {
        "tags": [
          "Marketplace"
        ],
        "summary": "List buy orders",
        "description": "This endpoint returns a paginated list of buy orders in the public marketplace.",
        "operationId": "ListBuyOrders",
        "security": [
          {
            "apikey": [
              "read:buy-orders"
            ]
          }
        ]
      }
    },
    "/api/v1/mint": {
      "post": {
        "tags": [
          "Mint"
        ],
        "summary": "Mint Assets",
        "description": "This endpoint allows for the minting of fungible and non-fungible assets.",
        "operationId": "MintAssets",
        "security": [
          {
            "apikey": [
              "mint:assets"
            ]
          }
        ]
      }
    },
    "/api/v1/orders/details": {
      "post": {
        "tags": [
          "Order"
        ],
        "summary": "Get Order Details (Not Implemented)",
        "description": "This endpoint allows for fetching details of an order to be signed.",
        "operationId": "OrderDetails"
      }
    },
    "/api/v1/orders": {
      "post": {
        "tags": [
          "Order"
        ],
        "summary": "Submit Order (Not Implemented)",
        "description": "This endpoint submits an order to the matching engine.",
        "operationId": "SubmitOrder"
      }
    },
    "/api/v1/orders/{orderId}": {
      "delete": {
        "tags": [
          "Order"
        ],
        "summary": "Cancel Order (Not Implemented)",
        "description": "This endpoint cancels an active order.",
        "operationId": "CancelOrder"
      }
    },
    "/api/v1/orderbooks": {
      "post": {
        "tags": [
          "Orderbook"
        ],
        "summary": "Create Orderbook (Not Implemented)",
        "description": "This endpoint creates an orderbook.",
        "operationId": "CreateOrderbook"
      }
    },
    "/api/v1/orderbooks/{orderbookId}": {
      "get": {
        "tags": [
          "Orderbook"
        ],
        "summary": "Get Orderbook (Not Implemented)",
        "description": "This endpoint fetches orderbook metadata by ID.",
        "operationId": "GetOrderbook"
      }
    },
    "/api/v1/orderbooks/{orderbookId}/l1": {
      "get": {
        "tags": [
          "Orderbook"
        ],
        "summary": "Get Orderbook L1 Data (Not Implemented)",
        "description": "This endpoint fetches orderbook level 1 data by ID.",
        "operationId": "GetOrderbookLevel1Data"
      }
    },
    "/api/v1/orderbooks/{orderbookId}/l2": {
      "get": {
        "tags": [
          "Orderbook"
        ],
        "summary": "Get Orderbook L2 Data (Not Implemented)",
        "description": "This endpoint fetches orderbook level 2 data by ID.",
        "operationId": "GetOrderbookLevel2Data"
      }
    },
    "/api/v1/settlements": {
      "post": {
        "tags": [
          "Settlement"
        ],
        "summary": "Submit Settlement",
        "description": "This endpoint submits an order settlement.",
        "operationId": "SubmitSettlement",
        "security": [
          {
            "apikey": [
              "write:settlements"
            ]
          }
        ]
      }
    },
    "/api/v1/assets": {
      "post": {
        "tags": [
          "Asset"
        ],
        "summary": "Enable Asset",
        "description": "This endpoint allows to enable an asset in the tenant system.",
        "operationId": "EnableAsset",
        "security": [
          {
            "apikey": [
              "write:tenant_assets"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Asset"
        ],
        "summary": "Get All Assets",
        "description": "This endpoint fetches all assets enabled in the tenant system, with support for filters and pagination.",
        "operationId": "GetAllAssets",
        "security": [
          {
            "apikey": [
              "read:tenant_assets"
            ]
          }
        ]
      }
    },
    "/api/v1/assets/disable": {
      "post": {
        "tags": [
          "Asset"
        ],
        "summary": "Disable Asset",
        "description": "This endpoint allows to disable an asset in the tenant system.",
        "operationId": "DisableAsset",
        "security": [
          {
            "apikey": [
              "write:tenant_assets"
            ]
          }
        ]
      }
    },
    "/api/v1/assets/{assetId}": {
      "get": {
        "tags": [
          "Asset"
        ],
        "summary": "Get Asset",
        "description": "This endpoint fetches a specific enabled asset by ID.",
        "operationId": "GetAsset",
        "security": [
          {
            "apikey": [
              "read:tenant_assets"
            ]
          }
        ]
      }
    },
    "/api/v1/assets/deploy": {
      "post": {
        "tags": [
          "Asset"
        ],
        "summary": "Deploy Asset",
        "description": "This endpoint allows for deploying an asset and enable it in the tenant system.",
        "operationId": "Deploy Asset",
        "security": [
          {
            "apikey": [
              "write:tenant_assets",
              "write:smart-contracts"
            ]
          }
        ]
      }
    },
    "/api/v1/assets/estimate-deploy": {
      "get": {
        "tags": [
          "Asset"
        ],
        "summary": "Estimate cost of the deployment for a new Asset",
        "description": "This endpoint allows for deploying an asset and enable it in the tenant system.",
        "operationId": "Estimate Asset Deploy Cost",
        "security": [
          {
            "apikey": [
              "write:tenant_assets",
              "write:smart-contracts"
            ]
          }
        ]
      }
    },
    "/api/v1/transactions": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "Get All Transactions",
        "description": "This endpoint fetches all transactions submitted by the system, with support for filters and pagination.",
        "operationId": "GetAllTransactions",
        "security": [
          {
            "apikey": [
              "read:transactions"
            ]
          }
        ]
      }
    },
    "/api/v1/transactions/{transactionId}": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "Get Transaction",
        "description": "This endpoint fetches a specific transaction by ID.",
        "operationId": "GetTransaction",
        "security": [
          {
            "apikey": [
              "read:transactions"
            ]
          }
        ]
      }
    },
    "/api/v1/transfers": {
      "post": {
        "tags": [
          "Transfer"
        ],
        "summary": "Transfer Asset",
        "description": "This endpoint allows for transferring assets between users.",
        "operationId": "Transfer",
        "security": [
          {
            "apikey": [
              "write:transfers"
            ]
          }
        ]
      }
    },
    "/api/v1/transfers/details": {
      "post": {
        "tags": [
          "Transfer"
        ],
        "summary": "Get Transfer Details",
        "description": "This endpoint allows for fetching details of a transfer to be signed (allocates a vault for the receiver)",
        "operationId": "TransferDetails",
        "security": [
          {
            "apikey": [
              "write:transfers"
            ]
          }
        ]
      }
    },
    "/api/v1/users": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Register new User",
        "description": "This endpoint registers a user.",
        "operationId": "RegisterUser",
        "security": [
          {
            "apikey": [
              "write:users"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get All Users",
        "description": "This endpoint fetches all users.",
        "operationId": "GetAllUsers",
        "security": [
          {
            "apikey": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/api/v1/users/register-details": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get EIP712 data to be signed",
        "description": "This endpoint return the typed data to be signed with EIP712 that is used on user registration.",
        "operationId": "EIP712Details",
        "security": [
          {
            "apikey": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/api/v1/users/{userId}": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Get User",
        "description": "This endpoint fetches a specific user by ID.",
        "operationId": "GetUser",
        "security": [
          {
            "apikey": [
              "read:users"
            ]
          }
        ]
      }
    },
    "/api/v1/vaults/deposit-details": {
      "post": {
        "tags": [
          "Deposit"
        ],
        "summary": "Returns the deposit details for a given asset.",
        "description": "This endpoint returns the deposit details for a given user, asset, and data availability mode.",
        "operationId": "DepositDetails",
        "security": [
          {
            "apikey": [
              "read:vaults",
              "write:vaults"
            ]
          }
        ]
      }
    },
    "/api/v1/vaults": {
      "get": {
        "tags": [
          "Vault"
        ],
        "summary": "Get All Vaults",
        "description": "This endpoint fetches all vaults in the system, with support for filters and pagination.",
        "operationId": "GetAllVaults",
        "security": [
          {
            "apikey": [
              "read:vaults"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Vault"
        ],
        "summary": "Allocate vault",
        "description": "This endpoint allocates a new vault for a given asset, if there isn't one already allocated.",
        "operationId": "AllocateVault",
        "security": [
          {
            "apikey": [
              "write:vaults"
            ]
          }
        ]
      }
    },
    "/api/v1/vaults/{vaultId}": {
      "get": {
        "tags": [
          "Vault"
        ],
        "summary": "Get a single Vault",
        "description": "This endpoint fetches a vault identified by its unique id.",
        "operationId": "GetVault",
        "security": [
          {
            "apikey": [
              "read:vaults"
            ]
          }
        ]
      }
    },
    "/api/v1/vaults/withdraw": {
      "post": {
        "tags": [
          "Withdraw"
        ],
        "summary": "Withdraw Asset",
        "description": "This endpoint allows for withdrawing assets from StarkExpress.",
        "operationId": "Withdraw",
        "security": [
          {
            "apikey": [
              "write:vaults"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "apikey": {
        "type": "apiKey",
        "description": "API Key Authentication",
        "name": "x-api-key",
        "in": "header"
      }
    }
  },
  "tags": [
    {
      "name": "User",
      "description": "Operations related with the user management."
    },
    {
      "name": "Asset",
      "description": "Operations related with the management of assets in the tenant system."
    },
    {
      "name": "Mint",
      "description": "Operations related with the minting of ERC-20, ERC-721 and ERC-1155 assets."
    },
    {
      "name": "Transfer",
      "description": "Operations related with the transfer of assets."
    },
    {
      "name": "Transaction",
      "description": "Operations related with the transactions submitted by the system."
    },
    {
      "name": "Withdraw",
      "description": "Operations related with the withdrawal of assets."
    },
    {
      "name": "Vault",
      "description": "Operations related with the vault management."
    },
    {
      "name": "Fee",
      "description": "Operations related with the configuration of the fee model in the tenant system."
    },
    {
      "name": "Orderbook",
      "description": "Operations related with the orderbook management."
    },
    {
      "name": "Order",
      "description": "Operations related with the order management."
    },
    {
      "name": "Settlement",
      "description": "Operations related with the settlement of assets."
    }
  ]
}