name: NPM Publish

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/node.js.yml

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Extract tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        env:
          GITHUB_REF: ${{ github.ref }}

      - run: ./src/packages/crypto/scripts/publish.sh ${{ steps.get_tag.outputs.TAG }}
        name: Publish crypto sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - run: ./src/packages/client/scripts/publish.sh ${{ steps.get_tag.outputs.TAG }}
        name: Publish client sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}

      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bundle.js
            bundle.min.js
