name: Npm nightly publish

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/node.js.yml

  publish-npm-dev:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: ./src/packages/crypto/scripts/publish-dev.sh
        name: Publish crypto sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - run: ./src/packages/client/scripts/publish-dev.sh
        name: Publish client sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}